// <auto-generated />
using Catalogo.Persistencia.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalogo.Persistencia.Database.Migrations
{
    [DbContext(typeof(AplicacionDBContext))]
    [Migration("20200521164620_Inicializacion")]
    partial class Inicializacion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalogo")
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalogo.Dominio.Producto", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductoID");

                    b.HasIndex("ProductoID");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoID = 1,
                            Descripcion = "Descripcion del producto 1",
                            Nombre = "Producto 1",
                            Precio = 5m
                        },
                        new
                        {
                            ProductoID = 2,
                            Descripcion = "Descripcion del producto 2",
                            Nombre = "Producto 2",
                            Precio = 4m
                        },
                        new
                        {
                            ProductoID = 3,
                            Descripcion = "Descripcion del producto 3",
                            Nombre = "Producto 3",
                            Precio = 9m
                        },
                        new
                        {
                            ProductoID = 4,
                            Descripcion = "Descripcion del producto 4",
                            Nombre = "Producto 4",
                            Precio = 5m
                        },
                        new
                        {
                            ProductoID = 5,
                            Descripcion = "Descripcion del producto 5",
                            Nombre = "Producto 5",
                            Precio = 1m
                        },
                        new
                        {
                            ProductoID = 6,
                            Descripcion = "Descripcion del producto 6",
                            Nombre = "Producto 6",
                            Precio = 7m
                        },
                        new
                        {
                            ProductoID = 7,
                            Descripcion = "Descripcion del producto 7",
                            Nombre = "Producto 7",
                            Precio = 6m
                        },
                        new
                        {
                            ProductoID = 8,
                            Descripcion = "Descripcion del producto 8",
                            Nombre = "Producto 8",
                            Precio = 6m
                        },
                        new
                        {
                            ProductoID = 9,
                            Descripcion = "Descripcion del producto 9",
                            Nombre = "Producto 9",
                            Precio = 7m
                        },
                        new
                        {
                            ProductoID = 10,
                            Descripcion = "Descripcion del producto 10",
                            Nombre = "Producto 10",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 11,
                            Descripcion = "Descripcion del producto 11",
                            Nombre = "Producto 11",
                            Precio = 1m
                        },
                        new
                        {
                            ProductoID = 12,
                            Descripcion = "Descripcion del producto 12",
                            Nombre = "Producto 12",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 13,
                            Descripcion = "Descripcion del producto 13",
                            Nombre = "Producto 13",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 14,
                            Descripcion = "Descripcion del producto 14",
                            Nombre = "Producto 14",
                            Precio = 9m
                        },
                        new
                        {
                            ProductoID = 15,
                            Descripcion = "Descripcion del producto 15",
                            Nombre = "Producto 15",
                            Precio = 4m
                        },
                        new
                        {
                            ProductoID = 16,
                            Descripcion = "Descripcion del producto 16",
                            Nombre = "Producto 16",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 17,
                            Descripcion = "Descripcion del producto 17",
                            Nombre = "Producto 17",
                            Precio = 9m
                        },
                        new
                        {
                            ProductoID = 18,
                            Descripcion = "Descripcion del producto 18",
                            Nombre = "Producto 18",
                            Precio = 7m
                        },
                        new
                        {
                            ProductoID = 19,
                            Descripcion = "Descripcion del producto 19",
                            Nombre = "Producto 19",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 20,
                            Descripcion = "Descripcion del producto 20",
                            Nombre = "Producto 20",
                            Precio = 9m
                        },
                        new
                        {
                            ProductoID = 21,
                            Descripcion = "Descripcion del producto 21",
                            Nombre = "Producto 21",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 22,
                            Descripcion = "Descripcion del producto 22",
                            Nombre = "Producto 22",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 23,
                            Descripcion = "Descripcion del producto 23",
                            Nombre = "Producto 23",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 24,
                            Descripcion = "Descripcion del producto 24",
                            Nombre = "Producto 24",
                            Precio = 8m
                        },
                        new
                        {
                            ProductoID = 25,
                            Descripcion = "Descripcion del producto 25",
                            Nombre = "Producto 25",
                            Precio = 5m
                        },
                        new
                        {
                            ProductoID = 26,
                            Descripcion = "Descripcion del producto 26",
                            Nombre = "Producto 26",
                            Precio = 4m
                        },
                        new
                        {
                            ProductoID = 27,
                            Descripcion = "Descripcion del producto 27",
                            Nombre = "Producto 27",
                            Precio = 6m
                        },
                        new
                        {
                            ProductoID = 28,
                            Descripcion = "Descripcion del producto 28",
                            Nombre = "Producto 28",
                            Precio = 7m
                        },
                        new
                        {
                            ProductoID = 29,
                            Descripcion = "Descripcion del producto 29",
                            Nombre = "Producto 29",
                            Precio = 7m
                        },
                        new
                        {
                            ProductoID = 30,
                            Descripcion = "Descripcion del producto 30",
                            Nombre = "Producto 30",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 31,
                            Descripcion = "Descripcion del producto 31",
                            Nombre = "Producto 31",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 32,
                            Descripcion = "Descripcion del producto 32",
                            Nombre = "Producto 32",
                            Precio = 1m
                        },
                        new
                        {
                            ProductoID = 33,
                            Descripcion = "Descripcion del producto 33",
                            Nombre = "Producto 33",
                            Precio = 7m
                        },
                        new
                        {
                            ProductoID = 34,
                            Descripcion = "Descripcion del producto 34",
                            Nombre = "Producto 34",
                            Precio = 8m
                        },
                        new
                        {
                            ProductoID = 35,
                            Descripcion = "Descripcion del producto 35",
                            Nombre = "Producto 35",
                            Precio = 7m
                        },
                        new
                        {
                            ProductoID = 36,
                            Descripcion = "Descripcion del producto 36",
                            Nombre = "Producto 36",
                            Precio = 8m
                        },
                        new
                        {
                            ProductoID = 37,
                            Descripcion = "Descripcion del producto 37",
                            Nombre = "Producto 37",
                            Precio = 4m
                        },
                        new
                        {
                            ProductoID = 38,
                            Descripcion = "Descripcion del producto 38",
                            Nombre = "Producto 38",
                            Precio = 8m
                        },
                        new
                        {
                            ProductoID = 39,
                            Descripcion = "Descripcion del producto 39",
                            Nombre = "Producto 39",
                            Precio = 5m
                        },
                        new
                        {
                            ProductoID = 40,
                            Descripcion = "Descripcion del producto 40",
                            Nombre = "Producto 40",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 41,
                            Descripcion = "Descripcion del producto 41",
                            Nombre = "Producto 41",
                            Precio = 4m
                        },
                        new
                        {
                            ProductoID = 42,
                            Descripcion = "Descripcion del producto 42",
                            Nombre = "Producto 42",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 43,
                            Descripcion = "Descripcion del producto 43",
                            Nombre = "Producto 43",
                            Precio = 9m
                        },
                        new
                        {
                            ProductoID = 44,
                            Descripcion = "Descripcion del producto 44",
                            Nombre = "Producto 44",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 45,
                            Descripcion = "Descripcion del producto 45",
                            Nombre = "Producto 45",
                            Precio = 7m
                        },
                        new
                        {
                            ProductoID = 46,
                            Descripcion = "Descripcion del producto 46",
                            Nombre = "Producto 46",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 47,
                            Descripcion = "Descripcion del producto 47",
                            Nombre = "Producto 47",
                            Precio = 6m
                        },
                        new
                        {
                            ProductoID = 48,
                            Descripcion = "Descripcion del producto 48",
                            Nombre = "Producto 48",
                            Precio = 6m
                        },
                        new
                        {
                            ProductoID = 49,
                            Descripcion = "Descripcion del producto 49",
                            Nombre = "Producto 49",
                            Precio = 1m
                        },
                        new
                        {
                            ProductoID = 50,
                            Descripcion = "Descripcion del producto 50",
                            Nombre = "Producto 50",
                            Precio = 9m
                        },
                        new
                        {
                            ProductoID = 51,
                            Descripcion = "Descripcion del producto 51",
                            Nombre = "Producto 51",
                            Precio = 6m
                        },
                        new
                        {
                            ProductoID = 52,
                            Descripcion = "Descripcion del producto 52",
                            Nombre = "Producto 52",
                            Precio = 6m
                        },
                        new
                        {
                            ProductoID = 53,
                            Descripcion = "Descripcion del producto 53",
                            Nombre = "Producto 53",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 54,
                            Descripcion = "Descripcion del producto 54",
                            Nombre = "Producto 54",
                            Precio = 4m
                        },
                        new
                        {
                            ProductoID = 55,
                            Descripcion = "Descripcion del producto 55",
                            Nombre = "Producto 55",
                            Precio = 7m
                        },
                        new
                        {
                            ProductoID = 56,
                            Descripcion = "Descripcion del producto 56",
                            Nombre = "Producto 56",
                            Precio = 4m
                        },
                        new
                        {
                            ProductoID = 57,
                            Descripcion = "Descripcion del producto 57",
                            Nombre = "Producto 57",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 58,
                            Descripcion = "Descripcion del producto 58",
                            Nombre = "Producto 58",
                            Precio = 1m
                        },
                        new
                        {
                            ProductoID = 59,
                            Descripcion = "Descripcion del producto 59",
                            Nombre = "Producto 59",
                            Precio = 9m
                        },
                        new
                        {
                            ProductoID = 60,
                            Descripcion = "Descripcion del producto 60",
                            Nombre = "Producto 60",
                            Precio = 7m
                        },
                        new
                        {
                            ProductoID = 61,
                            Descripcion = "Descripcion del producto 61",
                            Nombre = "Producto 61",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 62,
                            Descripcion = "Descripcion del producto 62",
                            Nombre = "Producto 62",
                            Precio = 9m
                        },
                        new
                        {
                            ProductoID = 63,
                            Descripcion = "Descripcion del producto 63",
                            Nombre = "Producto 63",
                            Precio = 9m
                        },
                        new
                        {
                            ProductoID = 64,
                            Descripcion = "Descripcion del producto 64",
                            Nombre = "Producto 64",
                            Precio = 5m
                        },
                        new
                        {
                            ProductoID = 65,
                            Descripcion = "Descripcion del producto 65",
                            Nombre = "Producto 65",
                            Precio = 1m
                        },
                        new
                        {
                            ProductoID = 66,
                            Descripcion = "Descripcion del producto 66",
                            Nombre = "Producto 66",
                            Precio = 1m
                        },
                        new
                        {
                            ProductoID = 67,
                            Descripcion = "Descripcion del producto 67",
                            Nombre = "Producto 67",
                            Precio = 5m
                        },
                        new
                        {
                            ProductoID = 68,
                            Descripcion = "Descripcion del producto 68",
                            Nombre = "Producto 68",
                            Precio = 5m
                        },
                        new
                        {
                            ProductoID = 69,
                            Descripcion = "Descripcion del producto 69",
                            Nombre = "Producto 69",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 70,
                            Descripcion = "Descripcion del producto 70",
                            Nombre = "Producto 70",
                            Precio = 6m
                        },
                        new
                        {
                            ProductoID = 71,
                            Descripcion = "Descripcion del producto 71",
                            Nombre = "Producto 71",
                            Precio = 8m
                        },
                        new
                        {
                            ProductoID = 72,
                            Descripcion = "Descripcion del producto 72",
                            Nombre = "Producto 72",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 73,
                            Descripcion = "Descripcion del producto 73",
                            Nombre = "Producto 73",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 74,
                            Descripcion = "Descripcion del producto 74",
                            Nombre = "Producto 74",
                            Precio = 8m
                        },
                        new
                        {
                            ProductoID = 75,
                            Descripcion = "Descripcion del producto 75",
                            Nombre = "Producto 75",
                            Precio = 6m
                        },
                        new
                        {
                            ProductoID = 76,
                            Descripcion = "Descripcion del producto 76",
                            Nombre = "Producto 76",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 77,
                            Descripcion = "Descripcion del producto 77",
                            Nombre = "Producto 77",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 78,
                            Descripcion = "Descripcion del producto 78",
                            Nombre = "Producto 78",
                            Precio = 1m
                        },
                        new
                        {
                            ProductoID = 79,
                            Descripcion = "Descripcion del producto 79",
                            Nombre = "Producto 79",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 80,
                            Descripcion = "Descripcion del producto 80",
                            Nombre = "Producto 80",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 81,
                            Descripcion = "Descripcion del producto 81",
                            Nombre = "Producto 81",
                            Precio = 7m
                        },
                        new
                        {
                            ProductoID = 82,
                            Descripcion = "Descripcion del producto 82",
                            Nombre = "Producto 82",
                            Precio = 9m
                        },
                        new
                        {
                            ProductoID = 83,
                            Descripcion = "Descripcion del producto 83",
                            Nombre = "Producto 83",
                            Precio = 6m
                        },
                        new
                        {
                            ProductoID = 84,
                            Descripcion = "Descripcion del producto 84",
                            Nombre = "Producto 84",
                            Precio = 8m
                        },
                        new
                        {
                            ProductoID = 85,
                            Descripcion = "Descripcion del producto 85",
                            Nombre = "Producto 85",
                            Precio = 6m
                        },
                        new
                        {
                            ProductoID = 86,
                            Descripcion = "Descripcion del producto 86",
                            Nombre = "Producto 86",
                            Precio = 6m
                        },
                        new
                        {
                            ProductoID = 87,
                            Descripcion = "Descripcion del producto 87",
                            Nombre = "Producto 87",
                            Precio = 8m
                        },
                        new
                        {
                            ProductoID = 88,
                            Descripcion = "Descripcion del producto 88",
                            Nombre = "Producto 88",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 89,
                            Descripcion = "Descripcion del producto 89",
                            Nombre = "Producto 89",
                            Precio = 1m
                        },
                        new
                        {
                            ProductoID = 90,
                            Descripcion = "Descripcion del producto 90",
                            Nombre = "Producto 90",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 91,
                            Descripcion = "Descripcion del producto 91",
                            Nombre = "Producto 91",
                            Precio = 7m
                        },
                        new
                        {
                            ProductoID = 92,
                            Descripcion = "Descripcion del producto 92",
                            Nombre = "Producto 92",
                            Precio = 4m
                        },
                        new
                        {
                            ProductoID = 93,
                            Descripcion = "Descripcion del producto 93",
                            Nombre = "Producto 93",
                            Precio = 8m
                        },
                        new
                        {
                            ProductoID = 94,
                            Descripcion = "Descripcion del producto 94",
                            Nombre = "Producto 94",
                            Precio = 7m
                        },
                        new
                        {
                            ProductoID = 95,
                            Descripcion = "Descripcion del producto 95",
                            Nombre = "Producto 95",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 96,
                            Descripcion = "Descripcion del producto 96",
                            Nombre = "Producto 96",
                            Precio = 5m
                        },
                        new
                        {
                            ProductoID = 97,
                            Descripcion = "Descripcion del producto 97",
                            Nombre = "Producto 97",
                            Precio = 3m
                        },
                        new
                        {
                            ProductoID = 98,
                            Descripcion = "Descripcion del producto 98",
                            Nombre = "Producto 98",
                            Precio = 4m
                        },
                        new
                        {
                            ProductoID = 99,
                            Descripcion = "Descripcion del producto 99",
                            Nombre = "Producto 99",
                            Precio = 2m
                        },
                        new
                        {
                            ProductoID = 100,
                            Descripcion = "Descripcion del producto 100",
                            Nombre = "Producto 100",
                            Precio = 7m
                        });
                });

            modelBuilder.Entity("Catalogo.Dominio.ProductoEnStock", b =>
                {
                    b.Property<int>("ProductoEnStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductoEnStockId");

                    b.HasIndex("ProductoId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductoEnStockId = 1,
                            ProductoId = 1,
                            Stock = 17
                        },
                        new
                        {
                            ProductoEnStockId = 2,
                            ProductoId = 2,
                            Stock = 8
                        },
                        new
                        {
                            ProductoEnStockId = 3,
                            ProductoId = 3,
                            Stock = 12
                        },
                        new
                        {
                            ProductoEnStockId = 4,
                            ProductoId = 4,
                            Stock = 11
                        },
                        new
                        {
                            ProductoEnStockId = 5,
                            ProductoId = 5,
                            Stock = 9
                        },
                        new
                        {
                            ProductoEnStockId = 6,
                            ProductoId = 6,
                            Stock = 8
                        },
                        new
                        {
                            ProductoEnStockId = 7,
                            ProductoId = 7,
                            Stock = 16
                        },
                        new
                        {
                            ProductoEnStockId = 8,
                            ProductoId = 8,
                            Stock = 17
                        },
                        new
                        {
                            ProductoEnStockId = 9,
                            ProductoId = 9,
                            Stock = 5
                        },
                        new
                        {
                            ProductoEnStockId = 10,
                            ProductoId = 10,
                            Stock = 0
                        },
                        new
                        {
                            ProductoEnStockId = 11,
                            ProductoId = 11,
                            Stock = 8
                        },
                        new
                        {
                            ProductoEnStockId = 12,
                            ProductoId = 12,
                            Stock = 15
                        },
                        new
                        {
                            ProductoEnStockId = 13,
                            ProductoId = 13,
                            Stock = 4
                        },
                        new
                        {
                            ProductoEnStockId = 14,
                            ProductoId = 14,
                            Stock = 16
                        },
                        new
                        {
                            ProductoEnStockId = 15,
                            ProductoId = 15,
                            Stock = 8
                        },
                        new
                        {
                            ProductoEnStockId = 16,
                            ProductoId = 16,
                            Stock = 14
                        },
                        new
                        {
                            ProductoEnStockId = 17,
                            ProductoId = 17,
                            Stock = 6
                        },
                        new
                        {
                            ProductoEnStockId = 18,
                            ProductoId = 18,
                            Stock = 8
                        },
                        new
                        {
                            ProductoEnStockId = 19,
                            ProductoId = 19,
                            Stock = 5
                        },
                        new
                        {
                            ProductoEnStockId = 20,
                            ProductoId = 20,
                            Stock = 12
                        },
                        new
                        {
                            ProductoEnStockId = 21,
                            ProductoId = 21,
                            Stock = 1
                        },
                        new
                        {
                            ProductoEnStockId = 22,
                            ProductoId = 22,
                            Stock = 9
                        },
                        new
                        {
                            ProductoEnStockId = 23,
                            ProductoId = 23,
                            Stock = 4
                        },
                        new
                        {
                            ProductoEnStockId = 24,
                            ProductoId = 24,
                            Stock = 2
                        },
                        new
                        {
                            ProductoEnStockId = 25,
                            ProductoId = 25,
                            Stock = 1
                        },
                        new
                        {
                            ProductoEnStockId = 26,
                            ProductoId = 26,
                            Stock = 2
                        },
                        new
                        {
                            ProductoEnStockId = 27,
                            ProductoId = 27,
                            Stock = 4
                        },
                        new
                        {
                            ProductoEnStockId = 28,
                            ProductoId = 28,
                            Stock = 8
                        },
                        new
                        {
                            ProductoEnStockId = 29,
                            ProductoId = 29,
                            Stock = 14
                        },
                        new
                        {
                            ProductoEnStockId = 30,
                            ProductoId = 30,
                            Stock = 19
                        },
                        new
                        {
                            ProductoEnStockId = 31,
                            ProductoId = 31,
                            Stock = 7
                        },
                        new
                        {
                            ProductoEnStockId = 32,
                            ProductoId = 32,
                            Stock = 16
                        },
                        new
                        {
                            ProductoEnStockId = 33,
                            ProductoId = 33,
                            Stock = 5
                        },
                        new
                        {
                            ProductoEnStockId = 34,
                            ProductoId = 34,
                            Stock = 19
                        },
                        new
                        {
                            ProductoEnStockId = 35,
                            ProductoId = 35,
                            Stock = 18
                        },
                        new
                        {
                            ProductoEnStockId = 36,
                            ProductoId = 36,
                            Stock = 11
                        },
                        new
                        {
                            ProductoEnStockId = 37,
                            ProductoId = 37,
                            Stock = 14
                        },
                        new
                        {
                            ProductoEnStockId = 38,
                            ProductoId = 38,
                            Stock = 7
                        },
                        new
                        {
                            ProductoEnStockId = 39,
                            ProductoId = 39,
                            Stock = 2
                        },
                        new
                        {
                            ProductoEnStockId = 40,
                            ProductoId = 40,
                            Stock = 4
                        },
                        new
                        {
                            ProductoEnStockId = 41,
                            ProductoId = 41,
                            Stock = 17
                        },
                        new
                        {
                            ProductoEnStockId = 42,
                            ProductoId = 42,
                            Stock = 14
                        },
                        new
                        {
                            ProductoEnStockId = 43,
                            ProductoId = 43,
                            Stock = 0
                        },
                        new
                        {
                            ProductoEnStockId = 44,
                            ProductoId = 44,
                            Stock = 7
                        },
                        new
                        {
                            ProductoEnStockId = 45,
                            ProductoId = 45,
                            Stock = 11
                        },
                        new
                        {
                            ProductoEnStockId = 46,
                            ProductoId = 46,
                            Stock = 1
                        },
                        new
                        {
                            ProductoEnStockId = 47,
                            ProductoId = 47,
                            Stock = 3
                        },
                        new
                        {
                            ProductoEnStockId = 48,
                            ProductoId = 48,
                            Stock = 13
                        },
                        new
                        {
                            ProductoEnStockId = 49,
                            ProductoId = 49,
                            Stock = 18
                        },
                        new
                        {
                            ProductoEnStockId = 50,
                            ProductoId = 50,
                            Stock = 19
                        },
                        new
                        {
                            ProductoEnStockId = 51,
                            ProductoId = 51,
                            Stock = 0
                        },
                        new
                        {
                            ProductoEnStockId = 52,
                            ProductoId = 52,
                            Stock = 4
                        },
                        new
                        {
                            ProductoEnStockId = 53,
                            ProductoId = 53,
                            Stock = 10
                        },
                        new
                        {
                            ProductoEnStockId = 54,
                            ProductoId = 54,
                            Stock = 11
                        },
                        new
                        {
                            ProductoEnStockId = 55,
                            ProductoId = 55,
                            Stock = 11
                        },
                        new
                        {
                            ProductoEnStockId = 56,
                            ProductoId = 56,
                            Stock = 7
                        },
                        new
                        {
                            ProductoEnStockId = 57,
                            ProductoId = 57,
                            Stock = 4
                        },
                        new
                        {
                            ProductoEnStockId = 58,
                            ProductoId = 58,
                            Stock = 9
                        },
                        new
                        {
                            ProductoEnStockId = 59,
                            ProductoId = 59,
                            Stock = 9
                        },
                        new
                        {
                            ProductoEnStockId = 60,
                            ProductoId = 60,
                            Stock = 6
                        },
                        new
                        {
                            ProductoEnStockId = 61,
                            ProductoId = 61,
                            Stock = 4
                        },
                        new
                        {
                            ProductoEnStockId = 62,
                            ProductoId = 62,
                            Stock = 7
                        },
                        new
                        {
                            ProductoEnStockId = 63,
                            ProductoId = 63,
                            Stock = 3
                        },
                        new
                        {
                            ProductoEnStockId = 64,
                            ProductoId = 64,
                            Stock = 5
                        },
                        new
                        {
                            ProductoEnStockId = 65,
                            ProductoId = 65,
                            Stock = 13
                        },
                        new
                        {
                            ProductoEnStockId = 66,
                            ProductoId = 66,
                            Stock = 12
                        },
                        new
                        {
                            ProductoEnStockId = 67,
                            ProductoId = 67,
                            Stock = 9
                        },
                        new
                        {
                            ProductoEnStockId = 68,
                            ProductoId = 68,
                            Stock = 5
                        },
                        new
                        {
                            ProductoEnStockId = 69,
                            ProductoId = 69,
                            Stock = 18
                        },
                        new
                        {
                            ProductoEnStockId = 70,
                            ProductoId = 70,
                            Stock = 16
                        },
                        new
                        {
                            ProductoEnStockId = 71,
                            ProductoId = 71,
                            Stock = 0
                        },
                        new
                        {
                            ProductoEnStockId = 72,
                            ProductoId = 72,
                            Stock = 19
                        },
                        new
                        {
                            ProductoEnStockId = 73,
                            ProductoId = 73,
                            Stock = 5
                        },
                        new
                        {
                            ProductoEnStockId = 74,
                            ProductoId = 74,
                            Stock = 1
                        },
                        new
                        {
                            ProductoEnStockId = 75,
                            ProductoId = 75,
                            Stock = 14
                        },
                        new
                        {
                            ProductoEnStockId = 76,
                            ProductoId = 76,
                            Stock = 6
                        },
                        new
                        {
                            ProductoEnStockId = 77,
                            ProductoId = 77,
                            Stock = 9
                        },
                        new
                        {
                            ProductoEnStockId = 78,
                            ProductoId = 78,
                            Stock = 16
                        },
                        new
                        {
                            ProductoEnStockId = 79,
                            ProductoId = 79,
                            Stock = 11
                        },
                        new
                        {
                            ProductoEnStockId = 80,
                            ProductoId = 80,
                            Stock = 19
                        },
                        new
                        {
                            ProductoEnStockId = 81,
                            ProductoId = 81,
                            Stock = 19
                        },
                        new
                        {
                            ProductoEnStockId = 82,
                            ProductoId = 82,
                            Stock = 11
                        },
                        new
                        {
                            ProductoEnStockId = 83,
                            ProductoId = 83,
                            Stock = 10
                        },
                        new
                        {
                            ProductoEnStockId = 84,
                            ProductoId = 84,
                            Stock = 15
                        },
                        new
                        {
                            ProductoEnStockId = 85,
                            ProductoId = 85,
                            Stock = 19
                        },
                        new
                        {
                            ProductoEnStockId = 86,
                            ProductoId = 86,
                            Stock = 3
                        },
                        new
                        {
                            ProductoEnStockId = 87,
                            ProductoId = 87,
                            Stock = 5
                        },
                        new
                        {
                            ProductoEnStockId = 88,
                            ProductoId = 88,
                            Stock = 13
                        },
                        new
                        {
                            ProductoEnStockId = 89,
                            ProductoId = 89,
                            Stock = 8
                        },
                        new
                        {
                            ProductoEnStockId = 90,
                            ProductoId = 90,
                            Stock = 10
                        },
                        new
                        {
                            ProductoEnStockId = 91,
                            ProductoId = 91,
                            Stock = 7
                        },
                        new
                        {
                            ProductoEnStockId = 92,
                            ProductoId = 92,
                            Stock = 5
                        },
                        new
                        {
                            ProductoEnStockId = 93,
                            ProductoId = 93,
                            Stock = 17
                        },
                        new
                        {
                            ProductoEnStockId = 94,
                            ProductoId = 94,
                            Stock = 15
                        },
                        new
                        {
                            ProductoEnStockId = 95,
                            ProductoId = 95,
                            Stock = 0
                        },
                        new
                        {
                            ProductoEnStockId = 96,
                            ProductoId = 96,
                            Stock = 10
                        },
                        new
                        {
                            ProductoEnStockId = 97,
                            ProductoId = 97,
                            Stock = 10
                        },
                        new
                        {
                            ProductoEnStockId = 98,
                            ProductoId = 98,
                            Stock = 14
                        },
                        new
                        {
                            ProductoEnStockId = 99,
                            ProductoId = 99,
                            Stock = 14
                        },
                        new
                        {
                            ProductoEnStockId = 100,
                            ProductoId = 100,
                            Stock = 18
                        });
                });

            modelBuilder.Entity("Catalogo.Dominio.ProductoEnStock", b =>
                {
                    b.HasOne("Catalogo.Dominio.Producto", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalogo.Dominio.ProductoEnStock", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
