// <auto-generated />
using Customer.Persistencia.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Customer.Persistencia.Database.Migrations
{
    [DbContext(typeof(AplicacionDBContext))]
    [Migration("20200526160752_iniciar3")]
    partial class iniciar3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Customer")
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Customer.Dominio.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ClienteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Nombre = "Juan Ruiz"
                        },
                        new
                        {
                            ClienteId = 2,
                            Nombre = "Juan Pacheco"
                        },
                        new
                        {
                            ClienteId = 3,
                            Nombre = "Juan Montoya"
                        },
                        new
                        {
                            ClienteId = 4,
                            Nombre = "Juan Velazques"
                        },
                        new
                        {
                            ClienteId = 5,
                            Nombre = "Juan Torres"
                        },
                        new
                        {
                            ClienteId = 6,
                            Nombre = "Juan Sánchez"
                        },
                        new
                        {
                            ClienteId = 7,
                            Nombre = "Juan García"
                        },
                        new
                        {
                            ClienteId = 8,
                            Nombre = "Juan Rodríguez"
                        },
                        new
                        {
                            ClienteId = 9,
                            Nombre = "Juan Andrade"
                        },
                        new
                        {
                            ClienteId = 10,
                            Nombre = "Juan Flores"
                        },
                        new
                        {
                            ClienteId = 11,
                            Nombre = "Carlos Ruiz"
                        },
                        new
                        {
                            ClienteId = 12,
                            Nombre = "Carlos Pacheco"
                        },
                        new
                        {
                            ClienteId = 13,
                            Nombre = "Carlos Montoya"
                        },
                        new
                        {
                            ClienteId = 14,
                            Nombre = "Carlos Velazques"
                        },
                        new
                        {
                            ClienteId = 15,
                            Nombre = "Carlos Torres"
                        },
                        new
                        {
                            ClienteId = 16,
                            Nombre = "Carlos Sánchez"
                        },
                        new
                        {
                            ClienteId = 17,
                            Nombre = "Carlos García"
                        },
                        new
                        {
                            ClienteId = 18,
                            Nombre = "Carlos Rodríguez"
                        },
                        new
                        {
                            ClienteId = 19,
                            Nombre = "Carlos Andrade"
                        },
                        new
                        {
                            ClienteId = 20,
                            Nombre = "Carlos Flores"
                        },
                        new
                        {
                            ClienteId = 21,
                            Nombre = "Leidy Ruiz"
                        },
                        new
                        {
                            ClienteId = 22,
                            Nombre = "Leidy Pacheco"
                        },
                        new
                        {
                            ClienteId = 23,
                            Nombre = "Leidy Montoya"
                        },
                        new
                        {
                            ClienteId = 24,
                            Nombre = "Leidy Velazques"
                        },
                        new
                        {
                            ClienteId = 25,
                            Nombre = "Leidy Torres"
                        },
                        new
                        {
                            ClienteId = 26,
                            Nombre = "Leidy Sánchez"
                        },
                        new
                        {
                            ClienteId = 27,
                            Nombre = "Leidy García"
                        },
                        new
                        {
                            ClienteId = 28,
                            Nombre = "Leidy Rodríguez"
                        },
                        new
                        {
                            ClienteId = 29,
                            Nombre = "Leidy Andrade"
                        },
                        new
                        {
                            ClienteId = 30,
                            Nombre = "Leidy Flores"
                        },
                        new
                        {
                            ClienteId = 31,
                            Nombre = "Paola Ruiz"
                        },
                        new
                        {
                            ClienteId = 32,
                            Nombre = "Paola Pacheco"
                        },
                        new
                        {
                            ClienteId = 33,
                            Nombre = "Paola Montoya"
                        },
                        new
                        {
                            ClienteId = 34,
                            Nombre = "Paola Velazques"
                        },
                        new
                        {
                            ClienteId = 35,
                            Nombre = "Paola Torres"
                        },
                        new
                        {
                            ClienteId = 36,
                            Nombre = "Paola Sánchez"
                        },
                        new
                        {
                            ClienteId = 37,
                            Nombre = "Paola García"
                        },
                        new
                        {
                            ClienteId = 38,
                            Nombre = "Paola Rodríguez"
                        },
                        new
                        {
                            ClienteId = 39,
                            Nombre = "Paola Andrade"
                        },
                        new
                        {
                            ClienteId = 40,
                            Nombre = "Paola Flores"
                        },
                        new
                        {
                            ClienteId = 41,
                            Nombre = "Juan Ruiz"
                        },
                        new
                        {
                            ClienteId = 42,
                            Nombre = "Juan Pacheco"
                        },
                        new
                        {
                            ClienteId = 43,
                            Nombre = "Juan Montoya"
                        },
                        new
                        {
                            ClienteId = 44,
                            Nombre = "Juan Velazques"
                        },
                        new
                        {
                            ClienteId = 45,
                            Nombre = "Juan Torres"
                        },
                        new
                        {
                            ClienteId = 46,
                            Nombre = "Juan Sánchez"
                        },
                        new
                        {
                            ClienteId = 47,
                            Nombre = "Juan García"
                        },
                        new
                        {
                            ClienteId = 48,
                            Nombre = "Juan Rodríguez"
                        },
                        new
                        {
                            ClienteId = 49,
                            Nombre = "Juan Andrade"
                        },
                        new
                        {
                            ClienteId = 50,
                            Nombre = "Juan Flores"
                        },
                        new
                        {
                            ClienteId = 51,
                            Nombre = "Diana Ruiz"
                        },
                        new
                        {
                            ClienteId = 52,
                            Nombre = "Diana Pacheco"
                        },
                        new
                        {
                            ClienteId = 53,
                            Nombre = "Diana Montoya"
                        },
                        new
                        {
                            ClienteId = 54,
                            Nombre = "Diana Velazques"
                        },
                        new
                        {
                            ClienteId = 55,
                            Nombre = "Diana Torres"
                        },
                        new
                        {
                            ClienteId = 56,
                            Nombre = "Diana Sánchez"
                        },
                        new
                        {
                            ClienteId = 57,
                            Nombre = "Diana García"
                        },
                        new
                        {
                            ClienteId = 58,
                            Nombre = "Diana Rodríguez"
                        },
                        new
                        {
                            ClienteId = 59,
                            Nombre = "Diana Andrade"
                        },
                        new
                        {
                            ClienteId = 60,
                            Nombre = "Diana Flores"
                        },
                        new
                        {
                            ClienteId = 61,
                            Nombre = "María Ruiz"
                        },
                        new
                        {
                            ClienteId = 62,
                            Nombre = "María Pacheco"
                        },
                        new
                        {
                            ClienteId = 63,
                            Nombre = "María Montoya"
                        },
                        new
                        {
                            ClienteId = 64,
                            Nombre = "María Velazques"
                        },
                        new
                        {
                            ClienteId = 65,
                            Nombre = "María Torres"
                        },
                        new
                        {
                            ClienteId = 66,
                            Nombre = "María Sánchez"
                        },
                        new
                        {
                            ClienteId = 67,
                            Nombre = "María García"
                        },
                        new
                        {
                            ClienteId = 68,
                            Nombre = "María Rodríguez"
                        },
                        new
                        {
                            ClienteId = 69,
                            Nombre = "María Andrade"
                        },
                        new
                        {
                            ClienteId = 70,
                            Nombre = "María Flores"
                        },
                        new
                        {
                            ClienteId = 71,
                            Nombre = "Kevin Ruiz"
                        },
                        new
                        {
                            ClienteId = 72,
                            Nombre = "Kevin Pacheco"
                        },
                        new
                        {
                            ClienteId = 73,
                            Nombre = "Kevin Montoya"
                        },
                        new
                        {
                            ClienteId = 74,
                            Nombre = "Kevin Velazques"
                        },
                        new
                        {
                            ClienteId = 75,
                            Nombre = "Kevin Torres"
                        },
                        new
                        {
                            ClienteId = 76,
                            Nombre = "Kevin Sánchez"
                        },
                        new
                        {
                            ClienteId = 77,
                            Nombre = "Kevin García"
                        },
                        new
                        {
                            ClienteId = 78,
                            Nombre = "Kevin Rodríguez"
                        },
                        new
                        {
                            ClienteId = 79,
                            Nombre = "Kevin Andrade"
                        },
                        new
                        {
                            ClienteId = 80,
                            Nombre = "Kevin Flores"
                        },
                        new
                        {
                            ClienteId = 81,
                            Nombre = "Bryan Ruiz"
                        },
                        new
                        {
                            ClienteId = 82,
                            Nombre = "Bryan Pacheco"
                        },
                        new
                        {
                            ClienteId = 83,
                            Nombre = "Bryan Montoya"
                        },
                        new
                        {
                            ClienteId = 84,
                            Nombre = "Bryan Velazques"
                        },
                        new
                        {
                            ClienteId = 85,
                            Nombre = "Bryan Torres"
                        },
                        new
                        {
                            ClienteId = 86,
                            Nombre = "Bryan Sánchez"
                        },
                        new
                        {
                            ClienteId = 87,
                            Nombre = "Bryan García"
                        },
                        new
                        {
                            ClienteId = 88,
                            Nombre = "Bryan Rodríguez"
                        },
                        new
                        {
                            ClienteId = 89,
                            Nombre = "Bryan Andrade"
                        },
                        new
                        {
                            ClienteId = 90,
                            Nombre = "Bryan Flores"
                        },
                        new
                        {
                            ClienteId = 91,
                            Nombre = "Ana Ruiz"
                        },
                        new
                        {
                            ClienteId = 92,
                            Nombre = "Ana Pacheco"
                        },
                        new
                        {
                            ClienteId = 93,
                            Nombre = "Ana Montoya"
                        },
                        new
                        {
                            ClienteId = 94,
                            Nombre = "Ana Velazques"
                        },
                        new
                        {
                            ClienteId = 95,
                            Nombre = "Ana Torres"
                        },
                        new
                        {
                            ClienteId = 96,
                            Nombre = "Ana Sánchez"
                        },
                        new
                        {
                            ClienteId = 97,
                            Nombre = "Ana García"
                        },
                        new
                        {
                            ClienteId = 98,
                            Nombre = "Ana Rodríguez"
                        },
                        new
                        {
                            ClienteId = 99,
                            Nombre = "Ana Andrade"
                        },
                        new
                        {
                            ClienteId = 100,
                            Nombre = "Ana Flores"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
